export const data = [
  {
    id: 1,
    image: "/revolver.jpeg",
    price: "₦400",
    title: "Revolver",
    description: "asdcfvgbhmk",
  },
  {
    id: 2,
    image: "/img1.jpeg",
    price: "₦360",
    title: "pistol",
    description: "Cz shadow 2 grip",
  },
  {
    id: 3,
    image: "/img2.jpeg",
    price: "₦599",
    title: "pistol",
    description: "The bretta x 92",
  },
  {
    id: 4,
    image: "/img3.jpeg",
    price: "₦567",
    title: "fdhdjujhd",
    description: "dyhdki",
  },
  {
    id: 5,
    image: "/img4.jpeg",
    price: "₦146",
    title: "ijxoik",
    description: "dxgvhkd",
  },
  {
    id: 6,
    image: "/img5.jpeg",
    price: "₦490",
    title: "dhkljkd",
    description: "dvyh",
  },
  {
    id: 7,
    image: "/img6.jpeg",
    price: "₦390",
    title: "dgjh,d",
    description: "dvyhik",
  },
  {
    id: 9,
    image: "/img7.jpeg",
    price: "₦599",
    title: "dstyuli",
    description: "dvyihl",
  },
  {
    id: 10,
    image: "/img8.jpeg",
    price: "₦572",
    title: "sgjl",
    description: "dsfk",
  },
  {
    id: 11,
    image: "/img9.jpeg",
    price: "₦349",
    title: "scdgj,",
    description: "dsgu,k",
  },
  {
    id: 12,
    image: "/img10.jpeg",
    price: "₦679",
    title: "dsgj",
    description: "dvhil",
  },
  {
    id: 13,
    image: "/img11.jpeg",
    price: "₦499",
    title: "dsgj",
    description: "xdsmk",
  },
  {
    id: 14,
    image: "/img12.jpeg",
    price: "₦099",
    title: "xctsku,",
    description: "xsfkyd",
  },
  {
    id: 15,
    image: "/img13.jpeg",
    price: "₦399",
    title: "ds,gl",
    description: "zzxrmjf",
  },
  {
    id: 16,
    image: "/img14.jpeg",
    price: "₦909",
    title: "sxfmj",
    description: "zdmgg",
  },
  {
    id: 17,
    image: "/img15.jpeg",
    price: "₦349",
    title: "zxcv",
    description: "zxcv",
  },
  {
    id: 18,
    image: "/img16.jpeg",
    price: "₦009",
    title: "zxcvb",
    description: "sdfgb",
  },
  {
    id: 19,
    image: "/img17.jpeg",
    price: "₦999",
    title: "sxdcvb",
    description: "sdfghj",
  },
];
